### PR TITLE
lmao

### PR DESCRIPTION
**Pull request by mohan-cao**
funny joke xD

### CODE REVIEW

**Comment by dan-wong** [comment]
Have you tested this to make sure it still fits inside the box?

**Comment by mohan-cao** [comment]
According to an ACM study (references on request), pull requests reviewers do not discriminate between tested and non-tested code

**Comment by dan-wong** [comment]
If you get rid of ENGSCI 111 or another subject I'll merge it, I think the box can only have three subjects in it

**Comment by mohan-cao** [comment]
@dan-wong fix plz

**Comment by dan-wong** [comment]
The text overflows, please fix

capture

**Pull request merged**
